name: authentication_api
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  function_tree: ^0.9.1
  provider: ^6.1.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  connectivity_plus: ^6.0.3
  battery_plus: ^6.0.1
  fluttertoast: ^8.2.6
  flutter_local_notifications: ^17.2.1+1
  http: ^1.2.1
  contacts_service: ^0.6.3
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  intl_translation: ^0.20.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/localization/intl_en.arb
    - lib/localization/intl_es.arb

  generate: true 