// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATU4rG6nx1WyMpF1iuiiCh_MlIoQ9_hg8',
    appId: '1:668813979866:web:7874d7dd1f0c3f65ee75e3',
    messagingSenderId: '668813979866',
    projectId: 'auth-flutter-b8eb7',
    authDomain: 'auth-flutter-b8eb7.firebaseapp.com',
    storageBucket: 'auth-flutter-b8eb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4mJJdtQAmtKNCkeHMBR-q2YhBYYOWVbU',
    appId: '1:668813979866:android:414d803f89d29dceee75e3',
    messagingSenderId: '668813979866',
    projectId: 'auth-flutter-b8eb7',
    storageBucket: 'auth-flutter-b8eb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwQRpmYpcblT9Z0PdTLHyJ96FQNqmdkIU',
    appId: '1:668813979866:ios:57760f060c486f3aee75e3',
    messagingSenderId: '668813979866',
    projectId: 'auth-flutter-b8eb7',
    storageBucket: 'auth-flutter-b8eb7.appspot.com',
    androidClientId: '668813979866-hlu7jn63krhhmm8pbcm6er5u8o36cd0t.apps.googleusercontent.com',
    iosClientId: '668813979866-qkp84rkoesih4lupi6nqud60i942qlqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwQRpmYpcblT9Z0PdTLHyJ96FQNqmdkIU',
    appId: '1:668813979866:ios:57760f060c486f3aee75e3',
    messagingSenderId: '668813979866',
    projectId: 'auth-flutter-b8eb7',
    storageBucket: 'auth-flutter-b8eb7.appspot.com',
    androidClientId: '668813979866-hlu7jn63krhhmm8pbcm6er5u8o36cd0t.apps.googleusercontent.com',
    iosClientId: '668813979866-qkp84rkoesih4lupi6nqud60i942qlqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATU4rG6nx1WyMpF1iuiiCh_MlIoQ9_hg8',
    appId: '1:668813979866:web:3d92dd63882736f8ee75e3',
    messagingSenderId: '668813979866',
    projectId: 'auth-flutter-b8eb7',
    authDomain: 'auth-flutter-b8eb7.firebaseapp.com',
    storageBucket: 'auth-flutter-b8eb7.appspot.com',
  );

}